language: python
python: 2.7
cache:
  directories:
  - "$HOME/.cache/pip"
  - "$HOME/.cache/lektor/builds"
env:
  global:
    - secure: |-
      draTHxSivg1+fVEAxs5OuJomtztaV0qUr0nOg4N0lXck09bQdraBg6s5W6mHEMy9zr
      0MqYEkCdpwKWnZCut5vnsOVnVomyFdsdfgjszuIk9u65elWuF4aGsU6Ri0++1qez5D
      jKeoLzSRTZ1+fc2ITFFlm3uiXfmHR3/W7qYmFYenfAUjyQJo9k20yt/XGVHMx1x5+m
      fVMKHGDB3ImQ3vOUl2H13BlJCqVap0pcfhRsm8tnUkRE4+Ktifw1IZx4XX17BeVcq+
      PlpQ/qNSTiKboQfLhwP1ALJMFQQf8ktXF9teJgd0A7PEDAZm8MzkD8PJ8O+H4/yCMG
      C3zOz11oEfp9ngGOh677AkE5XhTCxw3q3Ai5C/EeW398MUvH7CF5rHmQMhKeaKMtFZ
      IjNdw/ZYFU3m6iBhD16jDCSAMtAaCZK9mTHscOAtNps4IlUiEUBn9roL7gCeqEcxgk
      ImFkV4PREpVkhEh0CHaU2R9OHL0WhHymwkJ9v6SCNURZE6ecpjTHPHSV0M8IsTVn0c
      iigFfH5NDbkX7KcqZOUrlmE6Rq4oU5P3QyUpy0JKlCYVmNEZf5z/3J2FxqOR76RwLP
      gflLl2vHVZH/ioiJhCxoGGbYqDCGMMym6kws9+Ithh21SWMx146Uy/mdSOSHUxfCsF
      o8i6HmCv5Wk0Z65Kt/pLC5I=  # LEKTOR_DEPLOY_PASSWORD

install: pip install Lektor
script: lektor build
deploy:
  provider: script
  script: lektor deploy ghpages --username zupo --password $LEKTOR_DEPLOY_PASSWORD
  on:
    branch: master
